# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tankWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tankWindow(object):
    def setupUi(self, tankWindow):
        tankWindow.setObjectName("tankWindow")
        tankWindow.resize(1000, 720)
        tankWindow.setMinimumSize(QtCore.QSize(1000, 720))
        tankWindow.setMaximumSize(QtCore.QSize(1000, 720))
        self.widget = QtWidgets.QWidget(tankWindow)
        self.widget.setMinimumSize(QtCore.QSize(1000, 720))
        self.widget.setMaximumSize(QtCore.QSize(1000, 720))
        self.widget.setMouseTracking(True)
        self.widget.setObjectName("widget")
        self.tabMenuWidget = QtWidgets.QTabWidget(self.widget)
        self.tabMenuWidget.setGeometry(QtCore.QRect(0, 0, 1000, 660))
        self.tabMenuWidget.setMinimumSize(QtCore.QSize(1000, 660))
        self.tabMenuWidget.setMaximumSize(QtCore.QSize(1000, 660))
        self.tabMenuWidget.setBaseSize(QtCore.QSize(1021, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.tabMenuWidget.setFont(font)
        self.tabMenuWidget.setStyleSheet("color:#2F4056;")
        self.tabMenuWidget.setIconSize(QtCore.QSize(24, 24))
        self.tabMenuWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabMenuWidget.setObjectName("tabMenuWidget")
        self.tab_control = QtWidgets.QWidget()
        self.tab_control.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.tab_control.setFont(font)
        self.tab_control.setStyleSheet("")
        self.tab_control.setObjectName("tab_control")
        self.avoid = QtWidgets.QCheckBox(self.tab_control)
        self.avoid.setGeometry(QtCore.QRect(880, 40, 81, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.avoid.setFont(font)
        self.avoid.setObjectName("avoid")
        self.label_2 = QtWidgets.QLabel(self.tab_control)
        self.label_2.setGeometry(QtCore.QRect(760, 70, 91, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.car_backward = QtWidgets.QPushButton(self.tab_control)
        self.car_backward.setGeometry(QtCore.QRect(820, 290, 61, 51))
        self.car_backward.setStyleSheet("background-color:rgb(99, 180, 255);color:rgb(243, 243, 243);")
        self.car_backward.setObjectName("car_backward")
        self.keyboard_control = QtWidgets.QCheckBox(self.tab_control)
        self.keyboard_control.setGeometry(QtCore.QRect(880, 120, 81, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.keyboard_control.setFont(font)
        self.keyboard_control.setObjectName("keyboard_control")
        self.travel = QtWidgets.QCheckBox(self.tab_control)
        self.travel.setGeometry(QtCore.QRect(880, 80, 81, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.travel.setFont(font)
        self.travel.setObjectName("travel")
        self.car_rotate = QtWidgets.QPushButton(self.tab_control)
        self.car_rotate.setGeometry(QtCore.QRect(760, 340, 61, 51))
        self.car_rotate.setStyleSheet("background-color:rgb(255, 255, 127);color:rgb(66, 66, 66);")
        self.car_rotate.setObjectName("car_rotate")
        self.car_right = QtWidgets.QPushButton(self.tab_control)
        self.car_right.setGeometry(QtCore.QRect(760, 240, 61, 51))
        self.car_right.setStyleSheet("background-color:rgb(99, 180, 255);color:rgb(243, 243, 243);")
        self.car_right.setObjectName("car_right")
        self.label_4 = QtWidgets.QLabel(self.tab_control)
        self.label_4.setGeometry(QtCore.QRect(810, 150, 91, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgb(85, 170, 255)")
        self.label_4.setObjectName("label_4")
        self.car_cam_left = QtWidgets.QPushButton(self.tab_control)
        self.car_cam_left.setGeometry(QtCore.QRect(880, 490, 61, 51))
        self.car_cam_left.setStyleSheet("background-color:#01AAED;color:#F3F3F3;")
        self.car_cam_left.setObjectName("car_cam_left")
        self.car_forward = QtWidgets.QPushButton(self.tab_control)
        self.car_forward.setGeometry(QtCore.QRect(820, 190, 61, 51))
        self.car_forward.setWhatsThis("")
        self.car_forward.setStyleSheet("background-color:rgb(99, 180, 255);color:rgb(243, 243, 243);")
        self.car_forward.setObjectName("car_forward")
        self.car_cam_down = QtWidgets.QPushButton(self.tab_control)
        self.car_cam_down.setGeometry(QtCore.QRect(820, 440, 61, 51))
        self.car_cam_down.setStyleSheet("background-color:#01AAED;color:#F3F3F3;")
        self.car_cam_down.setObjectName("car_cam_down")
        self.label = QtWidgets.QLabel(self.tab_control)
        self.label.setGeometry(QtCore.QRect(760, 30, 91, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.car_stop = QtWidgets.QPushButton(self.tab_control)
        self.car_stop.setGeometry(QtCore.QRect(880, 340, 61, 51))
        self.car_stop.setStyleSheet("background-color:rgb(255, 85, 0);color:rgb(243, 243, 243);")
        self.car_stop.setObjectName("car_stop")
        self.car_cam_up = QtWidgets.QPushButton(self.tab_control)
        self.car_cam_up.setGeometry(QtCore.QRect(820, 540, 61, 51))
        self.car_cam_up.setStyleSheet("background-color:#01AAED;color:#F3F3F3;")
        self.car_cam_up.setObjectName("car_cam_up")
        self.label_3 = QtWidgets.QLabel(self.tab_control)
        self.label_3.setGeometry(QtCore.QRect(760, 110, 91, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.tab_control)
        self.label_5.setGeometry(QtCore.QRect(800, 400, 111, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgb(85, 170, 255)")
        self.label_5.setObjectName("label_5")
        self.car_cam_right = QtWidgets.QPushButton(self.tab_control)
        self.car_cam_right.setGeometry(QtCore.QRect(760, 490, 61, 51))
        self.car_cam_right.setStyleSheet("background-color:#01AAED;color:#F3F3F3;")
        self.car_cam_right.setObjectName("car_cam_right")
        self.car_left = QtWidgets.QPushButton(self.tab_control)
        self.car_left.setGeometry(QtCore.QRect(880, 240, 61, 51))
        self.car_left.setStyleSheet("background-color:rgb(99, 180, 255);color:rgb(243, 243, 243);")
        self.car_left.setObjectName("car_left")
        self.label_9 = QtWidgets.QLabel(self.tab_control)
        self.label_9.setGeometry(QtCore.QRect(270, 540, 101, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.camera_switch = QtWidgets.QCheckBox(self.tab_control)
        self.camera_switch.setGeometry(QtCore.QRect(400, 550, 81, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.camera_switch.setFont(font)
        self.camera_switch.setObjectName("camera_switch")
        self.origin_camera = QtWidgets.QLabel(self.tab_control)
        self.origin_camera.setGeometry(QtCore.QRect(60, 50, 640, 480))
        self.origin_camera.setStyleSheet("background-color:#F2F2F2")
        self.origin_camera.setText("")
        self.origin_camera.setObjectName("origin_camera")
        self.tabMenuWidget.addTab(self.tab_control, "")
        self.tab_voice = QtWidgets.QWidget()
        self.tab_voice.setStyleSheet("background-color:rgba(255,255,255,0.8);")
        self.tab_voice.setObjectName("tab_voice")
        self.voice_control = QtWidgets.QPushButton(self.tab_voice)
        self.voice_control.setGeometry(QtCore.QRect(820, 80, 81, 41))
        self.voice_control.setObjectName("voice_control")
        self.voice_text_composite = QtWidgets.QPushButton(self.tab_voice)
        self.voice_text_composite.setGeometry(QtCore.QRect(780, 150, 81, 41))
        self.voice_text_composite.setObjectName("voice_text_composite")
        self.voice_text_chat = QtWidgets.QPushButton(self.tab_voice)
        self.voice_text_chat.setGeometry(QtCore.QRect(780, 480, 81, 41))
        self.voice_text_chat.setObjectName("voice_text_chat")
        self.label_6 = QtWidgets.QLabel(self.tab_voice)
        self.label_6.setGeometry(QtCore.QRect(150, 40, 501, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.input_composite_text = QtWidgets.QLineEdit(self.tab_voice)
        self.input_composite_text.setGeometry(QtCore.QRect(150, 150, 591, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.input_composite_text.setFont(font)
        self.input_composite_text.setObjectName("input_composite_text")
        self.voice_chat = QtWidgets.QPushButton(self.tab_voice)
        self.voice_chat.setGeometry(QtCore.QRect(690, 40, 81, 41))
        self.voice_chat.setObjectName("voice_chat")
        self.voice_chat_list = QtWidgets.QTextBrowser(self.tab_voice)
        self.voice_chat_list.setGeometry(QtCore.QRect(150, 230, 711, 251))
        self.voice_chat_list.setStyleSheet("text-align:center;font-size:15px;padding-left:150px;line-height:40px;")
        self.voice_chat_list.setObjectName("voice_chat_list")
        self.input_send_text = QtWidgets.QLineEdit(self.tab_voice)
        self.input_send_text.setGeometry(QtCore.QRect(150, 480, 631, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.input_send_text.setFont(font)
        self.input_send_text.setObjectName("input_send_text")
        self.label_7 = QtWidgets.QLabel(self.tab_voice)
        self.label_7.setGeometry(QtCore.QRect(150, 80, 651, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.voice_audio_start = QtWidgets.QPushButton(self.tab_voice)
        self.voice_audio_start.setGeometry(QtCore.QRect(560, 550, 81, 41))
        self.voice_audio_start.setObjectName("voice_audio_start")
        self.label_8 = QtWidgets.QLabel(self.tab_voice)
        self.label_8.setGeometry(QtCore.QRect(150, 550, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.voice_audio_stop = QtWidgets.QPushButton(self.tab_voice)
        self.voice_audio_stop.setGeometry(QtCore.QRect(670, 550, 81, 41))
        self.voice_audio_stop.setObjectName("voice_audio_stop")
        self.voice_audio_play = QtWidgets.QPushButton(self.tab_voice)
        self.voice_audio_play.setGeometry(QtCore.QRect(780, 550, 81, 41))
        self.voice_audio_play.setObjectName("voice_audio_play")
        self.tabMenuWidget.addTab(self.tab_voice, "")
        self.tab_video = QtWidgets.QWidget()
        self.tab_video.setObjectName("tab_video")
        self.camera_origin = QtWidgets.QPushButton(self.tab_video)
        self.camera_origin.setGeometry(QtCore.QRect(800, 180, 81, 31))
        self.camera_origin.setObjectName("camera_origin")
        self.camera_face = QtWidgets.QPushButton(self.tab_video)
        self.camera_face.setGeometry(QtCore.QRect(800, 250, 81, 31))
        self.camera_face.setObjectName("camera_face")
        self.camera_eyes = QtWidgets.QPushButton(self.tab_video)
        self.camera_eyes.setGeometry(QtCore.QRect(800, 320, 81, 31))
        self.camera_eyes.setObjectName("camera_eyes")
        self.camera_close = QtWidgets.QPushButton(self.tab_video)
        self.camera_close.setGeometry(QtCore.QRect(800, 390, 81, 31))
        self.camera_close.setObjectName("camera_close")
        self.video_pannel = QtWidgets.QLabel(self.tab_video)
        self.video_pannel.setGeometry(QtCore.QRect(80, 70, 640, 480))
        self.video_pannel.setStyleSheet("backgroud-color:#F2F2F2")
        self.video_pannel.setText("")
        self.video_pannel.setObjectName("video_pannel")
        self.tabMenuWidget.addTab(self.tab_video, "")
        self.tab_code = QtWidgets.QWidget()
        self.tab_code.setObjectName("tab_code")
        self.tabMenuWidget.addTab(self.tab_code, "")
        tankWindow.setCentralWidget(self.widget)
        self.menuBar = QtWidgets.QMenuBar(tankWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1000, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menuBar.setFont(font)
        self.menuBar.setStyleSheet("background-color:#01AAED;color:#F1F1F1;width:80px;")
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setStyleSheet("width:95px;border:2px solid #F1F1F1;")
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setStyleSheet("width:95px;border:2px solid #F1F1F1;")
        self.menu_2.setObjectName("menu_2")
        tankWindow.setMenuBar(self.menuBar)
        self.actionExit = QtWidgets.QAction(tankWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionChange = QtWidgets.QAction(tankWindow)
        self.actionChange.setObjectName("actionChange")
        self.actionExplain = QtWidgets.QAction(tankWindow)
        self.actionExplain.setObjectName("actionExplain")
        self.actionLogin = QtWidgets.QAction(tankWindow)
        self.actionLogin.setObjectName("actionLogin")
        self.menu.addAction(self.actionLogin)
        self.menu.addAction(self.actionChange)
        self.menu.addAction(self.actionExit)
        self.menu_2.addAction(self.actionExplain)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())

        self.retranslateUi(tankWindow)
        self.tabMenuWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(tankWindow)

    def retranslateUi(self, tankWindow):
        _translate = QtCore.QCoreApplication.translate
        tankWindow.setWindowTitle(_translate("tankWindow", "人工智能履带坦克"))
        self.avoid.setText(_translate("tankWindow", "开启"))
        self.label_2.setText(_translate("tankWindow", "循迹模式"))
        self.car_backward.setText(_translate("tankWindow", "后退"))
        self.keyboard_control.setText(_translate("tankWindow", "开启"))
        self.travel.setText(_translate("tankWindow", "开启"))
        self.car_rotate.setText(_translate("tankWindow", "旋转"))
        self.car_right.setText(_translate("tankWindow", "向左"))
        self.label_4.setText(_translate("tankWindow", "行动控制"))
        self.car_cam_left.setText(_translate("tankWindow", "向右"))
        self.car_forward.setText(_translate("tankWindow", "前进"))
        self.car_cam_down.setText(_translate("tankWindow", "向上"))
        self.label.setText(_translate("tankWindow", "避障模式"))
        self.car_stop.setText(_translate("tankWindow", "停止"))
        self.car_cam_up.setText(_translate("tankWindow", "向下"))
        self.label_3.setText(_translate("tankWindow", "键盘控制"))
        self.label_5.setText(_translate("tankWindow", "摄像头控制"))
        self.car_cam_right.setText(_translate("tankWindow", "向左"))
        self.car_left.setText(_translate("tankWindow", "向右"))
        self.label_9.setText(_translate("tankWindow", "摄像头画面"))
        self.camera_switch.setText(_translate("tankWindow", "开启"))
        self.tabMenuWidget.setTabText(self.tabMenuWidget.indexOf(self.tab_control), _translate("tankWindow", "运动控制"))
        self.voice_control.setText(_translate("tankWindow", "语音控制"))
        self.voice_text_composite.setText(_translate("tankWindow", "语音合成"))
        self.voice_text_chat.setText(_translate("tankWindow", "文字对话"))
        self.label_6.setText(_translate("tankWindow", "语音对话：唤醒词为佩奇佩奇，唤醒成功后听到提示音进行语音对话。"))
        self.input_composite_text.setPlaceholderText(_translate("tankWindow", "   语音合成会将输入的文字合成语音并播放，请输入文字..."))
        self.voice_chat.setText(_translate("tankWindow", "语音对话"))
        self.input_send_text.setPlaceholderText(_translate("tankWindow", "   请输入聊天文字内容..."))
        self.label_7.setText(_translate("tankWindow", "语音控制：唤醒词为佩奇佩奇，唤醒成功后说前进、后退、左转、右转、旋转等进行控制。"))
        self.voice_audio_start.setText(_translate("tankWindow", "录音"))
        self.label_8.setText(_translate("tankWindow", "录音播放：使用车载麦克阵列及音箱进行录音及播放。"))
        self.voice_audio_stop.setText(_translate("tankWindow", "停止录音"))
        self.voice_audio_play.setText(_translate("tankWindow", "播放"))
        self.tabMenuWidget.setTabText(self.tabMenuWidget.indexOf(self.tab_voice), _translate("tankWindow", "语音技术"))
        self.camera_origin.setText(_translate("tankWindow", "原始画面"))
        self.camera_face.setText(_translate("tankWindow", "人脸识别"))
        self.camera_eyes.setText(_translate("tankWindow", "眼部识别"))
        self.camera_close.setText(_translate("tankWindow", "关闭"))
        self.tabMenuWidget.setTabText(self.tabMenuWidget.indexOf(self.tab_video), _translate("tankWindow", "视频处理"))
        self.tabMenuWidget.setTabText(self.tabMenuWidget.indexOf(self.tab_code), _translate("tankWindow", "代码编辑"))
        self.menu.setTitle(_translate("tankWindow", "设备"))
        self.menu_2.setTitle(_translate("tankWindow", "关于"))
        self.actionExit.setText(_translate("tankWindow", "退出"))
        self.actionChange.setText(_translate("tankWindow", "切换"))
        self.actionExplain.setText(_translate("tankWindow", "使用说明"))
        self.actionLogin.setText(_translate("tankWindow", "登录"))
